import requests

BASE_URL = "http://localhost:3000"
AUTH_ENDPOINT = "/api/auth/callback/credentials"
PROJECTS_ENDPOINT = "/app/actions/project.ts"
FINANCE_SUMMARY_ENDPOINT = "/app/actions/finance.ts"

# Replace these with valid test user credentials for authentication
TEST_USER_CREDENTIALS = {
    "username": "testuser",
    "password": "testpassword"
}

def authenticate_user():
    try:
        resp = requests.post(
            BASE_URL + AUTH_ENDPOINT,
            json={
                "username": TEST_USER_CREDENTIALS["username"],
                "password": TEST_USER_CREDENTIALS["password"]
            },
            timeout=30
        )
        resp.raise_for_status()
        try:
            resp_json = resp.json()
        except requests.JSONDecodeError as e:
            assert False, f"Authentication response is not valid JSON: {e}"
        token = resp_json.get("token") or resp_json.get("accessToken") or resp_json.get("jwt")
        assert token, "Authentication response does not contain token"
        return token
    except requests.RequestException as e:
        assert False, f"Authentication request failed: {e}"
    except AssertionError as ve:
        assert False, str(ve)


def create_project(token, client_id):
    project_data = {
        "name": "Test Project for Finance Summary",
        "clientId": client_id,
        "startDate": "2024-01-01",
        "endDate": "2024-12-31",
        "description": "Autogenerated project for testing",
        "architecturalWorkflow": "basic"
    }
    headers = {
        "Authorization": f"Bearer {token}"
    }

    try:
        resp = requests.post(
            BASE_URL + PROJECTS_ENDPOINT,
            json=project_data,
            headers=headers,
            timeout=30
        )
        resp.raise_for_status()
        project_created = resp.json()
        assert project_created.get("id"), "Project creation response missing 'id'"
        return project_created["id"]
    except requests.RequestException as e:
        assert False, f"Project creation failed: {e}"


def create_client(token):
    client_data = {
        "name": "Test Client for Finance Summary",
        "email": "finance_test_client@example.com",
        "document": "FIN12345",
        "phone": "1234567890",
        "address": "123 Test St, Test City"
    }
    headers = {
        "Authorization": f"Bearer {token}"
    }
    try:
        resp = requests.post(
            BASE_URL + "/app/actions/client.ts",
            json=client_data,
            headers=headers,
            timeout=30
        )
        resp.raise_for_status()
        created_client = resp.json()
        assert created_client.get("id"), "Client creation response missing 'id'"
        return created_client["id"]
    except requests.RequestException as e:
        assert False, f"Client creation failed: {e}"

def delete_project(token, project_id):
    headers = {
        "Authorization": f"Bearer {token}"
    }
    try:
        resp = requests.delete(
            f"{BASE_URL}/app/actions/project.ts/{project_id}",
            headers=headers,
            timeout=30
        )
        if resp.status_code not in [200, 204]:
            print(f"Warning: Failed to delete project {project_id}, status {resp.status_code}")
    except requests.RequestException as e:
        print(f"Warning: Exception during project deletion: {e}")

def delete_client(token, client_id):
    headers = {
        "Authorization": f"Bearer {token}"
    }
    try:
        resp = requests.delete(
            f"{BASE_URL}/app/actions/client.ts/{client_id}",
            headers=headers,
            timeout=30
        )
        if resp.status_code not in [200, 204]:
            print(f"Warning: Failed to delete client {client_id}, status {resp.status_code}")
    except requests.RequestException as e:
        print(f"Warning: Exception during client deletion: {e}")

def test_get_financial_summary_with_authenticated_user_and_valid_project():
    token = authenticate_user()
    project_id = None
    client_id = None

    headers = {
        "Authorization": f"Bearer {token}"
    }

    client_id = create_client(token)
    try:
        project_id = create_project(token, client_id)
        params = {"projectId": project_id}
        try:
            resp = requests.get(
                BASE_URL + FINANCE_SUMMARY_ENDPOINT,
                headers=headers,
                params=params,
                timeout=30
            )
            resp.raise_for_status()
            data = resp.json()
            assert resp.status_code == 200
            assert "income" in data, "Income field missing in financial summary"
            assert "expenses" in data, "Expenses field missing in financial summary"
            assert "cashFlow" in data or "cash_flow" in data, "Cash flow field missing in financial summary"

            income_val = data.get("income")
            expenses_val = data.get("expenses")
            cash_flow_val = data.get("cashFlow") or data.get("cash_flow")

            assert income_val is not None, "Income value is None"
            assert expenses_val is not None, "Expenses value is None"
            assert cash_flow_val is not None, "Cash flow value is None"

        except requests.RequestException as e:
            assert False, f"Failed to get financial summary: {e}"
    finally:
        if project_id:
            delete_project(token, project_id)
        if client_id:
            delete_client(token, client_id)


test_get_financial_summary_with_authenticated_user_and_valid_project()
